---

sudo: required
language: python
services:
  - docker
before_install:
  - sudo apt-get -qq update
install:
  - pip install 'ansible<2.5'
  - pip install molecule
  - pip install docker-py
script:
  - molecule test
