---

- name: directory
  file:
    path: "{{ pva_dest_folder }}"
    state: directory

- name: download
  get_url:
    url: "{{ _pva_download.url }}"
    checksum: "{{ _pva_download.checksum }}"
    dest: "{{ pva_dest_folder }}/{{ _pva_basename }}"

- name: privileged
  become: true
  become_user: root
  when: ansible_os_family == 'RedHat'
  block:
    - name: install
      yum:
        name: "{{ pva_dest_folder | expanduser }}/{{ _pva_basename }}"
      when: ansible_distribution != 'Fedora'
    - name: install
      dnf:
        name: "{{ pva_dest_folder | expanduser }}/{{ _pva_basename }}"
      when: ansible_distribution == 'Fedora'

- name: privileged
  become: true
  become_user: root
  when: ansible_os_family == 'Debian'
  block:
    - name: install
      apt:
        deb: "{{ pva_dest_folder | expanduser }}/{{ _pva_basename }}"
