---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: .yamllint
platforms:
  - name: m-centos7
    image: centos:7
  - name: m-fedora26
    image: fedora:26
  - name: m-fedora27
    image: fedora:27
  - name: m-fedora28
    image: fedora:28
  - name: m-xenial
    image: ubuntu:16.04
  - name: m-artful
    image: ubuntu:17.10
  - name: m-bionic
    image: ubuntu:18.04
provisioner:
  name: ansible
  playbooks:
    create: ../default/create.yml
    destroy: ../default/destroy.yml
    prepare: prepare.yml
    converge: playbook.yml
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
