---

- name: proxy
  hosts: all
  tasks:
    - name: register proxy settings
      when: lookup('env', 'PROXY') == 'true'
      set_fact:
        proxy_setting:
          environment:
            http_proxy: "{{ lookup('env', 'PROXY_HTTP') }}"
            https_proxy: "{{ lookup('env', 'PROXY_HTTPS') }}"
          proxy_cert_path: "{{ lookup('env', 'PROXY_CERT_PATH') }}"
    # ca-certificates needs sudo
    # (we need to install package before enabling proxy, else it can trigger
    # ssl certificate errors)
    - name: sudo
      when: install_certs
      package:
        name: sudo
    - name: register proxy ssl certificate
      when: install_certs
      include_role:
        name: bdellegrazie.ca-certificates
      vars:
        ca_certificates_trusted:
          - name: proxy
            pem: "{{ lookup('file', proxy_setting.proxy_cert_path) }}"
  vars:
    install_certs: >
      proxy_setting is defined
      and proxy_setting.proxy_cert_path != ''

- name: Converge
  hosts: all
  environment:
    - "{{ proxy_setting.environment if proxy_setting is defined else {} }}"
  tasks:
    - name: powo.vagrant
      include_role:
        name: powo.vagrant
